# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/asus/sdm660-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter X00TD X01BD,$(TARGET_DEVICE)),)

endif
